### PR TITLE
Fixes remaining issues with integration tests, workflows, and regex.

### LINKED ISSUE #1: Add tests using volttron-testing
Port over [tests from modular volttron](https://github.com/VOLTTRON/volttron/tree/main/services/core/PlatformDriverAgent/platform_driver/interfaces/modbus_tk/tests), using the [volttron-testing library](https://github.com/VOLTTRON/volttron-testing)

### LINKED ISSUE #4: Fix code scanning alert - Overly permissive regular expression range
Tracking issue for:
- [ ] https://github.com/eclipse-volttron/volttron-lib-modbustk-driver/security/code-scanning/2

See if this can be less permissive for the regular expression.

### LINKED ISSUE #6: Add the auto-assign workflow to the .github actions in main and develop and others that are standard.

### PR DESCRIPTION
**Pull request by davidraker**
Fixes #6 , fixes #4 , fixes #1

### CODE REVIEW

**Comment by craigpnnl** [comment]
@davidraker  this should go to develop right?

**Comment by davidraker** [comment]
@craig8 Yep, fixed it.

**Comment by craigpnnl** [comment]
@davidraker you missed some of the main workflows [dispatch-to-pypi.yml](https://github.com/eclipse-volttron/volttron-core/blob/main/.github/workflows/dispatch-to-pypi.yml),
deploy-pre-release.yml especially.

**Comment by davidraker** [comment]
@craig8 deploy-pre-release is there.... Mine does have "publish-to-pypi" instead of "dispatch-to-pypi". That appears to be really similar with a line or two difference between them.  This is what is in the github-tooling repository. Should I be replacing whatever is in the workflows with whatever is in volttron-core instead of github-tooling?

**Comment by craigpnnl** [comment]
Dispatch to pypi is different being that it publishes on demand and its how we push releases to pypi.

I will update github tooling to be what should be standard.

**Pull request merged**
